coverage:
  precision: 2
  round: down
  range: "70...100"

status:
  project:
    default:
      target: auto
      threshold: 5%
  patch:
    default:
      target: 70%

ignore:
  - "coverage/**"
  - "dist/**"
  - "node_modules/**"
  - "tests/**"
